# Generated by Django 3.2.5 on 2021-07-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
